### ISSUE TITLE
moodle 3.0 and 3.1

### ISSUE THREAD

**Issue by pfautrero** [geogebra/moodle-qtype_geogebra#2]
Hi,

Do you plan to support last moodle versions ? 

Thanks

**Comment by cmiic** [comment]
The question type reportedly works with 3.0. You should also be fine with 3.1. I'm just doing the testing at the moment and clear the plugin in the plugins database for 3.1 today (if everything goes well, otherwise in a few days)

The assign submission should work with 3.0 and needs a minor upgrade for 3.1, which will be released today testing is OK, otherwise in a few days)

**Comment by cmiic** [comment]
Should be fixed with the latest release.
